NavfnROS:
  allow_unknown: true              # 未知の領域を経路に含めるかどうか（true/false）
  planner_window_x: 0.0            # プランナーの検索幅（x方向、m単位）
  planner_window_y: 0.0            # プランナーの検索幅（y方向、m単位）
  default_tolerance: 0.0           # 経路計画で許容される目標位置の誤差
  use_astar: false                 # A*アルゴリズムを使用するかどうか（true/false）
  allow_obs_planning: false        # 障害物を考慮した経路計画を行うか（true/false）
  visualize_potential: true       # 経路計画中にポテンシャルを可視化するかどうか
