global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true

  plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: state_layer, type: "potbot_nav::StateLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: lidar camera
    lidar: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
    camera: {sensor_frame: camera_link, data_type: PointCloud2, topic: camera/depth/points, marking: true, clearing: true, min_obstacle_height: 0.05}
    
  state_layer:
    observation_sources: lidar
    lidar: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
    prediction_time: 2.5
  